# Generated by Django 5.1.15 on 2026-08-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_subservice_job_category'),
        ('legal_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxlitigation',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_tax_litigation_jobs', to='clients.task'),
        ),
        migrations.AddField(
            model_name='tdslitigation',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_litigation_jobs', to='clients.task'),
        ),
    ]
