# Generated by Django 5.1.15 on 2026-08-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0002_incometaxlitigation_task_tdslitigation_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='litigation_type',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
