# Generated by Django 5.1.15 on 2026-08-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0003_documentcategory_litigation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcase',
            name='din_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='notice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='officer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='ph_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtcasestatuslog',
            name='din_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courtcasestatuslog',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtcasestatuslog',
            name='notice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtcasestatuslog',
            name='officer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courtcasestatuslog',
            name='ph_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
