# Generated by Django 5.1.15 on 2026-08-07 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0004_courtcase_din_number_courtcase_notice_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcaseauditlog',
            name='event_type',
            field=models.CharField(choices=[('case_created', 'Case Created'), ('info_update', 'Information Updated'), ('doc_upload', 'Document Uploaded'), ('doc_delete', 'Document Deleted'), ('status_change', 'Status Changed'), ('assignment', 'Maker/Checker Assigned'), ('activity_update', 'Case Details Updated'), ('note', 'Note'), ('notice_created', 'Notice Created'), ('notice_doc_uploaded', 'Notice Document Uploaded'), ('notice_doc_approved', 'Notice Document Approved'), ('notice_doc_rejected', 'Notice Document Rejected'), ('notice_doc_escalated', 'Notice Document Escalated'), ('notice_status_changed', 'Notice Status Changed'), ('notice_closed', 'Notice Closed')], max_length=30),
        ),
        migrations.CreateModel(
            name='CaseNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('din_number', models.CharField(blank=True, max_length=100, null=True)),
                ('officer', models.CharField(blank=True, max_length=200, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('extended_due_date', models.DateField(blank=True, null=True)),
                ('ph_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('wip', 'WIP'), ('open', 'Open'), ('closed', 'Closed')], default='wip', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='legal_services.courtcase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notice_documents/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('doc_type', models.CharField(choices=[('court_notice', 'Court Notice'), ('pending', 'Pending Review'), ('reply', 'Approved Reply')], default='pending', max_length=20)),
                ('review_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated to CEO')], default='not_applicable', max_length=20)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='legal_services.casenotice')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_notice_docs', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_notice_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
