# Generated by Django 5.1.15 on 2026-08-07 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0005_alter_legalcaseauditlog_event_type_casenotice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casenotice',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casenotice',
            name='review_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='casenotice',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casenotice',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_notices', to=settings.AUTH_USER_MODEL),
        ),
    ]
