# Generated by Django 5.1.15 on 2026-08-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0007_noticereply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcaseauditlog',
            name='event_type',
            field=models.CharField(choices=[('case_created', 'Case Created'), ('info_update', 'Information Updated'), ('doc_upload', 'Document Uploaded'), ('doc_delete', 'Document Deleted'), ('status_change', 'Status Changed'), ('assignment', 'Maker/Checker Assigned'), ('activity_update', 'Case Details Updated'), ('note', 'Note'), ('notice_created', 'Notice Created'), ('notice_doc_uploaded', 'Notice Document Uploaded'), ('notice_doc_approved', 'Notice Document Approved'), ('notice_doc_rejected', 'Notice Document Rejected'), ('notice_doc_escalated', 'Notice Document Escalated'), ('notice_doc_deleted', 'Notice Document Deleted'), ('notice_status_changed', 'Notice Status Changed'), ('notice_closed', 'Notice Closed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='noticereply',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='draft', max_length=20),
        ),
    ]
