# Generated by Django 5.1.15 on 2026-08-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0008_alter_legalcaseauditlog_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticedocument',
            name='doc_type',
            field=models.CharField(choices=[('court_notice', 'Court Notice'), ('pending', 'Pending Review'), ('reply', 'Approved Reply'), ('acknowledgment', 'Acknowledgment')], default='pending', max_length=20),
        ),
    ]
