# Generated by Django 5.1.15 on 2026-08-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0009_alter_noticedocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticereply',
            name='is_final_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reviewrequest',
            name='action_type',
            field=models.CharField(choices=[('summary', 'Summary Update'), ('step', 'Daily Update'), ('appeal', 'Submit Appeal'), ('adjournment', 'Log Adjournment'), ('notice_edit', 'Notice Info Edit')], max_length=20),
        ),
    ]
