# Generated by Django 5.1.15 on 2026-08-19 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0010_noticereply_is_final_reply_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcase',
            name='closure_review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='closure_review_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated to CEO')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='closure_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='closure_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_closure_bundles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='closure_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='closure_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_closure_bundles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casenotice',
            name='status',
            field=models.CharField(choices=[('wip', 'WIP'), ('under_review', 'Under Review'), ('open', 'Open')], default='wip', max_length=20),
        ),
        migrations.CreateModel(
            name='CaseClosureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('order', 'Order'), ('demand_notice', 'Demand Notice'), ('computation_sheet', 'Computation Sheet')], max_length=30)),
                ('file', models.FileField(upload_to='case_closure/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('court_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_documents', to='legal_services.courtcase')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_closure_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doc_type', '-uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('court_case', 'doc_type'), name='unique_closure_doc_per_type')],
            },
        ),
    ]
