# Generated by Django 5.1.15 on 2026-08-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0011_courtcase_closure_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticedocument',
            name='reply_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticedocument',
            name='doc_type',
            field=models.CharField(choices=[('court_notice', 'Court Notice'), ('pending', 'Pending Review'), ('reply', 'Approved Reply'), ('acknowledgment', 'Acknowledgment'), ('supporting_doc', 'Supporting Document')], default='pending', max_length=20),
        ),
    ]
