# Generated by Django 5.1.15 on 2026-09-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0012_noticedocument_reply_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcaseauditlog',
            name='event_type',
            field=models.CharField(choices=[('case_created', 'Case Created'), ('info_update', 'Information Updated'), ('doc_upload', 'Document Uploaded'), ('doc_delete', 'Document Deleted'), ('status_change', 'Status Changed'), ('assignment', 'Maker/Checker Assigned'), ('activity_update', 'Case Details Updated'), ('note', 'Note'), ('notice_created', 'Notice Created'), ('notice_doc_uploaded', 'Sent for Review'), ('notice_doc_approved', 'Approved'), ('notice_doc_rejected', 'Rejected'), ('notice_doc_escalated', 'Moved to CEO'), ('notice_doc_deleted', 'Document Deleted'), ('notice_status_changed', 'Notice Status Changed'), ('notice_closed', 'Notice Closed'), ('court_notice_uploaded', 'Court Notice Uploaded'), ('reply_uploaded', 'Reply Uploaded'), ('support_doc_uploaded', 'Supporting Doc Uploaded'), ('ack_uploaded', 'Acknowledgment Uploaded'), ('reply_approved', 'Reply Approved'), ('reply_rejected', 'Reply Rejected'), ('reply_escalated', 'Reply Moved to CEO'), ('ack_approved', 'Acknowledgment Approved'), ('ack_rejected', 'Acknowledgment Rejected'), ('ack_escalated', 'Acknowledgment Moved to CEO'), ('closure_submitted', 'Closure Submitted'), ('closure_approved', 'Case Closed'), ('closure_rejected', 'Closure Rejected'), ('closure_escalated', 'Closure Moved to CEO')], max_length=30),
        ),
        migrations.AlterField(
            model_name='noticedocument',
            name='doc_type',
            field=models.CharField(choices=[('court_notice', 'Court Notice'), ('pending', 'Pending Review'), ('reply', 'Approved Reply'), ('acknowledgment', 'Acknowledgment'), ('supporting_doc', 'Supporting Document'), ('pending_support', 'Pending Support Doc')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='noticedocument',
            name='review_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated to CEO')], default='not_applicable', max_length=20),
        ),
    ]
