# Generated by Django 5.1.15 on 2026-09-07 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_subservice_job_category'),
        ('legal_services', '0014_alter_legalcaseauditlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mcacase',
            name='financial_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mcacase',
            name='sub_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mca_cases', to='clients.subservice'),
        ),
        migrations.AddField(
            model_name='mcacase',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mca_cases', to='clients.task'),
        ),
        migrations.AlterField(
            model_name='legalcaseauditlog',
            name='event_type',
            field=models.CharField(choices=[('case_created', 'Case Created'), ('info_update', 'Information Updated'), ('doc_upload', 'Document Uploaded'), ('doc_delete', 'Document Deleted'), ('status_change', 'Status Changed'), ('assignment', 'Maker/Checker Assigned'), ('activity_update', 'Case Details Updated'), ('note', 'Note'), ('notice_created', 'Notice Created'), ('court_notice_deleted', 'Court Notice Deleted'), ('notice_doc_uploaded', 'Sent for Review'), ('notice_doc_approved', 'Approved'), ('notice_doc_rejected', 'Rejected'), ('notice_doc_escalated', 'Moved to CEO'), ('notice_doc_deleted', 'Document Deleted'), ('notice_status_changed', 'Notice Status Changed'), ('notice_closed', 'Notice Closed'), ('court_notice_uploaded', 'Court Notice Uploaded'), ('reply_uploaded', 'Reply Uploaded'), ('support_doc_uploaded', 'Supporting Doc Uploaded'), ('ack_uploaded', 'Acknowledgment Uploaded'), ('reply_approved', 'Reply Approved'), ('reply_rejected', 'Reply Rejected'), ('reply_escalated', 'Reply Moved to CEO'), ('ack_approved', 'Acknowledgment Approved'), ('ack_rejected', 'Acknowledgment Rejected'), ('ack_escalated', 'Acknowledgment Moved to CEO'), ('closure_submitted', 'Closure Submitted'), ('closure_approved', 'Case Closed'), ('closure_rejected', 'Closure Rejected'), ('closure_escalated', 'Closure Moved to CEO'), ('mca_filing_created', 'MCA Filing Created'), ('mca_draft_uploaded', 'MCA Draft Form Uploaded'), ('mca_docs_submitted', 'MCA Docs Submitted for Review'), ('mca_docs_approved', 'MCA Docs Approved for Filing'), ('mca_docs_rejected', 'MCA Docs Rejected'), ('mca_docs_escalated', 'MCA Docs Moved to CEO'), ('mca_srn_uploaded', 'MCA SRN Receipt Uploaded'), ('mca_srn_approved', 'MCA SRN Verified'), ('mca_srn_rejected', 'MCA SRN Rejected'), ('mca_srn_escalated', 'MCA SRN Moved to CEO'), ('mca_outcome_approved', 'MCA Outcome: Approved'), ('mca_outcome_rejected', 'MCA Outcome: Rejected'), ('mca_outcome_resubmit', 'MCA Outcome: Resubmission Required'), ('mca_filing_closed', 'MCA Filing Closed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='legalcaseauditlog',
            name='litigation_type',
            field=models.CharField(choices=[('tds', 'TDS'), ('income-tax', 'Income Tax'), ('mca', 'MCA')], max_length=20),
        ),
        migrations.CreateModel(
            name='MCAFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('filing_due_date', models.DateField(blank=True, null=True)),
                ('extended_due_date', models.DateField(blank=True, null=True)),
                ('srn_number', models.CharField(blank=True, max_length=100, null=True)),
                ('challan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('wip', 'WIP'), ('under_review', 'Under Review'), ('approved_for_filing', 'Approved for Filing'), ('filed_on_portal', 'Filed on Portal'), ('mca_approved', 'MCA Approved'), ('mca_rejected', 'MCA Rejected'), ('resubmission_required', 'Resubmission Required')], default='wip', max_length=30)),
                ('stage', models.CharField(choices=[('internal_review', 'Internal Review'), ('portal_filing', 'Portal Filing'), ('mca_verification', 'MCA Verification'), ('closed', 'Closed')], default='internal_review', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='not_applicable', max_length=20)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('srn_review_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='not_applicable', max_length=20)),
                ('srn_review_note', models.TextField(blank=True, null=True)),
                ('srn_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('mca_outcome', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_required', 'Resubmission Required')], default='pending', max_length=30)),
                ('mca_outcome_note', models.TextField(blank=True, null=True)),
                ('mca_outcome_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mca_filings', to=settings.AUTH_USER_MODEL)),
                ('mca_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='legal_services.mcacase')),
                ('mca_outcome_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mca_outcome_recorded_filings', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mca_filings', to=settings.AUTH_USER_MODEL)),
                ('srn_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srn_reviewed_mca_filings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCAFilingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mca_filings/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('doc_type', models.CharField(choices=[('draft_form', 'Draft Form (from MCA Portal)'), ('supporting_doc', 'Supporting Document'), ('pending_draft', 'Pending Draft'), ('pending_support', 'Pending Support Doc'), ('signed_form', 'Signed Form'), ('srn_receipt', 'SRN Receipt'), ('challan', 'Challan'), ('acknowledgment', 'Acknowledgment'), ('mca_approval_cert', 'MCA Approval Certificate'), ('mca_rejection_notice', 'MCA Rejection Notice'), ('resubmission_notice', 'Resubmission Notice')], default='pending_draft', max_length=30)),
                ('parent_draft', models.IntegerField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated to CEO')], default='draft', max_length=20)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='legal_services.mcafiling')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mca_docs', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_mca_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
