# Generated by Django 5.1.15 on 2026-09-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0041_alter_attendance_unique_together_and_more'),
        ('legal_services', '0015_mcacase_financial_year_mcacase_sub_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcacase',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='mcacase',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='+', to='employee.employee'),
        ),
    ]
