# Generated by Django 5.1.15 on 2026-09-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0016_remove_mcacase_assigned_to_mcacase_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcacase',
            name='status',
            field=models.CharField(choices=[('wip', 'WIP'), ('under_review', 'Under Review'), ('closed', 'Closed')], default='wip', max_length=20),
        ),
    ]
