# Generated by Django 5.1.15 on 2026-09-11 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0017_alter_mcacase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mcacase',
            name='service_group',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('llp', 'LLP')], db_index=True, default='company', max_length=20),
        ),
        migrations.CreateModel(
            name='FirmMCACredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
