# Generated by Django 5.1.15 on 2026-09-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0018_mcacase_service_group_firmmcacredential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirmMCACredential',
        ),
    ]
