# Generated by Django 5.2.1 on 2025-05-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_holiday_alter_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='ctc',
        ),
    ]
