# Generated by Django 5.2.2 on 2025-06-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_fileupload_recipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
