# Generated by Django 5.2.2 on 2025-06-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_delete_fileupload_delete_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='day',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
