# Generated by Django 5.2.2 on 2025-06-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_holiday_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='working_days_in_month',
            field=models.IntegerField(default=0),
        ),
    ]
