# Generated by Django 5.2.5 on 2025-11-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_company_team_leaverequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approval_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
