# Generated by Django 5.2.5 on 2025-11-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_leaverequest_approval_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='remaining_leave',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='total_leave',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='used_leave',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='comp_off',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='last_accrual',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='paid_leave',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
