# Generated by Django 5.2.5 on 2025-11-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_employeedocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedocument',
            name='document_name',
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to='employee_docs/'),
        ),
    ]
