# Generated by Django 5.2.5 on 2025-12-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_remove_employeedocument_document_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_picture',
        ),
    ]
