# Generated by Django 5.2.5 on 2025-12-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_remove_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employee_pics/'),
        ),
    ]
