# Generated by Django 5.2.5 on 2025-12-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_employee_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_picture',
        ),
    ]
