# Generated by Django 5.2.5 on 2025-12-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_remove_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_session',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
    ]
