# Generated by Django 5.2.5 on 2025-12-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_leaverequest_half_day_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_required_hours',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='employee',
            name='fixed_end_time',
            field=models.TimeField(blank=True, help_text='Required if work_type is fixed', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fixed_start_time',
            field=models.TimeField(blank=True, help_text='Required if work_type is fixed', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_type',
            field=models.CharField(choices=[('fixed', 'Fixed Time'), ('flexible', 'Flexible Time')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('holiday', 'Holiday'), ('comp_off', 'Comp Off'), ('sunday', 'Sunday')], default='present', max_length=20),
        ),
    ]
