# Generated by Django 5.2.5 on 2025-12-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_employee_daily_required_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='custom_timings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_same_timing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_week_type',
            field=models.CharField(choices=[('5_days', '5 Days (Mon-Fri)'), ('6_days', '6 Days (Mon-Sat)')], default='5_days', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fixed_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fixed_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
