# Generated by Django 5.2.5 on 2026-01-29 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_employee_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(blank=True, max_length=20, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_mode', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('proof', models.FileField(blank=True, null=True, upload_to='reimbursements/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('HEAD_APPROVED', 'Head Approved'), ('HEAD_REJECTED', 'Head Rejected'), ('PAID', 'Paid')], default='SUBMITTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reimbursements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
