# Generated by Django 5.2.5 on 2026-01-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Manager Approved', 'Manager Approved'), ('Manager Rejected', 'Manager Rejected'), ('Head Approved', 'Head Approved'), ('Head Rejected', 'Head Rejected'), ('Paid', 'Paid')], default='Submitted', max_length=50),
        ),
    ]
