# Generated by Django 5.2.5 on 2026-02-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_reimbursement_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
