# Generated by Django 5.2.5 on 2026-02-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0031_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCalendarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saturday_holiday', models.CharField(choices=[('none', 'No Saturdays Off'), ('all', 'All Saturdays Off'), ('1st', '1st Saturday Off'), ('2nd', '2nd Saturday Off'), ('3rd', '3rd Saturday Off'), ('4th', '4th Saturday Off'), ('1st_3rd', '1st & 3rd Saturday Off'), ('2nd_4th', '2nd & 4th Saturday Off')], default='none', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Calendar Config',
            },
        ),
    ]
