# Generated by Django 5.2.5 on 2026-04-30 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_reimbursement_founder_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursement',
            name='founder_approved_by',
        ),
        migrations.RemoveField(
            model_name='reimbursement',
            name='manager_approved_by',
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Manager Approved', 'Manager Approved'), ('Manager Rejected', 'Manager Rejected'), ('Head Approved', 'Head Approved'), ('Head Rejected', 'Head Rejected'), ('Paid', 'Paid')], default='Submitted', max_length=50),
        ),
        migrations.CreateModel(
            name='ReimbursementSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_manager_setting', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_setting_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reimbursement Setting',
            },
        ),
    ]
