# Generated by Django 5.2.5 on 2026-05-04 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0034_remove_reimbursement_founder_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='founder_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founder_approved_reimbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_reimbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Manager Approved', 'Manager Approved'), ('Manager Rejected', 'Manager Rejected'), ('Founder Approved', 'Founder Approved'), ('Founder Rejected', 'Founder Rejected'), ('Paid', 'Paid'), ('Head Rejected', 'Head Rejected')], default='Submitted', max_length=50),
        ),
    ]
