# Generated by Django 5.2.5 on 2026-05-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_reimbursement_founder_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='expense_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='from_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='misc_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='to_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='transport_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='payment_mode',
            field=models.CharField(default='Salary Slip', max_length=20),
        ),
    ]
