# # Generated by Django 5.2.5 on 2026-06-11 10:33

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('employee', '0037_alter_attendance_status_wfhrequest'),
#     ]

#     operations = [
#         migrations.RenameField(
#             model_name='wfhrequest',
#             old_name='date',
#             new_name='start_date',
#         ),
#         migrations.AlterUniqueTogether(
#             name='wfhrequest',
#             unique_together=set(),
#         ),
#         migrations.AddField(
#             model_name='wfhrequest',
#             name='end_date',
#             field=models.DateField(default='2025-01-01'),
#             preserve_default=False,
#         ),
#     ]



# Replace the ENTIRE contents of:
# employee/migrations/0038_rename_date_wfhrequest_start_date_and_more.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_alter_attendance_status_wfhrequest'),
    ]

    operations = [

        # ── Step 1: Only end_date is missing — add it ─────────────────────────
        migrations.RunSQL(
            sql="ALTER TABLE employee_wfhrequest ADD COLUMN `end_date` DATE NOT NULL DEFAULT '2025-01-01';",
            reverse_sql="ALTER TABLE employee_wfhrequest DROP COLUMN `end_date`;",
        ),

        # ── Step 2: Drop the temporary default ────────────────────────────────
        migrations.RunSQL(
            sql="ALTER TABLE employee_wfhrequest ALTER COLUMN `end_date` DROP DEFAULT;",
            reverse_sql="",
        ),

        # ── Step 3: Sync Django state — no DB operations ──────────────────────
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='wfhrequest',
                    unique_together=set(),
                ),
                migrations.RemoveField(
                    model_name='wfhrequest',
                    name='date',
                ),
                migrations.AddField(
                    model_name='wfhrequest',
                    name='start_date',
                    field=models.DateField(default='2025-01-01'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='wfhrequest',
                    name='end_date',
                    field=models.DateField(default='2025-01-01'),
                    preserve_default=False,
                ),
            ],
            database_operations=[],
        ),
    ]