# Generated by Django 5.2.5 on 2026-06-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_leavecancelrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecancelrequest',
            name='cancel_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
