# Generated by Django 5.1.15 on 2026-08-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='job_category',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
